#!/bin/bash

TF_CFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))') )
TF_LFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))') )

g++ -std=c++11 -shared octree_conv.cc  -o octree_conv.so -fPIC ${TF_CFLAGS[@]} ${TF_LFLAGS[@]} -O2

g++ -std=c++11 -shared octree_pooling.cc  -o octree_pooling.so -fPIC ${TF_CFLAGS[@]} ${TF_LFLAGS[@]} -O2

g++ -std=c++11 -shared octree_full_layer.cc  -o octree_full_layer.so -fPIC ${TF_CFLAGS[@]} ${TF_LFLAGS[@]} -O2

g++ -std=c++11 -shared octree_full_layer_gradient.cc -o octree_full_layer.so -fPIC ${TF_CFLAGS[@]} ${TF_LFLAGS[@]} -O2
